### PR TITLE
fix: status response on await deposit is more than a plain string

### PR DESCRIPTION
**Pull request by juliswer**

### CODE REVIEW

**Comment by Kodylow** [comment]
did you test this and confirm it works?

**Comment by juliswer** [comment]
> did you test this and confirm it works?

Yes, I made a few attempts and all of them gave me the following object:

`"Confirmed": {
        "btc_transaction": {
            "version": 2,
            "lock_time": 930424,
            "input": [
                {
                    "previous_output": "df72e60bb11ee4161edeb8350b79ea40951c61d8e03e3cee36fe3aca08a35d73:1",
                    "script_sig": "",
                    "sequence": 4294967293,
                    "witness": [
                        "304402203014e41273f3d2b17df0d3ba563cf47d739c0bbf735dd80891a5cf5e2c98a49f02207f63cb2be463bd714a664a80d821db0c1726d73d3ab2f5aa65aefc30c511ff5901",
                        "029f1f05fc0c021a49971bd1be2ab81d09ef5992c48f1ca847fe1bbaf9d5458dc8"
                    ]
                }
            ],
            "output": [
                {
                    "value": 312383880,
                    "script_pubkey": "0014f3a3feaca63fda384905dce49d6e850d5baa98d6"
                },
                {
                    "value": 100000,
                    "script_pubkey": "00205b16cc54e5f9e7680e04f4ffa1bd63b879f47d58bd5f436ec00265a16c269e40"
                }
            ]
        },
        "out_idx": 1
    }`

**Comment by juliswer** [comment]
> did you test this and confirm it works?

https://github.com/Kodylow/fedimint-ts/assets/63827661/6422d6cd-cf29-41a1-b660-ca787cb699b3

**Comment by Kodylow** [comment]
Awesome ty, just confirmed locally, merging

**Pull request merged**
